{
  self,
  inputs,
  ...
}: {
  flake.nixosModules.elowenHardware =
    # Do not modify this file!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }: {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod"];
      boot.initrd.kernelModules = [];
      boot.kernelModules = ["kvm-intel"];
      boot.extraModulePackages = [];

      fileSystems."/" = {
        device = "/dev/disk/by-uuid/c404aed6-5a0c-46b9-9cee-a438717b0645";
        fsType = "btrfs";
        options = ["subvol=@"];
      };

      fileSystems."/.snapshots" = {
        device = "/dev/disk/by-uuid/c404aed6-5a0c-46b9-9cee-a438717b0645";
        fsType = "btrfs";
        options = ["subvol=@snapshots"];
      };

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/12CE-A600";
        fsType = "vfat";
        options = ["fmask=0077" "dmask=0077"];
      };

      fileSystems."/home" = {
        device = "/dev/disk/by-uuid/c404aed6-5a0c-46b9-9cee-a438717b0645";
        fsType = "btrfs";
        options = ["subvol=@home"];
      };

      fileSystems."/nix" = {
        device = "/dev/disk/by-uuid/c404aed6-5a0c-46b9-9cee-a438717b0645";
        fsType = "btrfs";
        options = ["subvol=@nix"];
      };

      swapDevices = [
        {device = "/dev/disk/by-uuid/808a32b5-05f2-4ec3-851b-f6846d27ac77";}
      ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
